import Head from "next/head";
import React, {useState} from "react";
import {Menu} from "antd";
import Image from 'next/image';
import Link from "next/link";

const items = [

    {
        label: (
            <Link href="/rooms"   rel="noopener noreferrer">
                Liste de mes rooms
            </Link>
        ),
        key: 'rooms',
    },
    {
        label: (
            <Link href="/inscription"   rel="noopener noreferrer" >
                Inscription
            </Link>
        ),
        key: 'incrit',

    },
    {
        label: (
            <Link href="/connexion"   rel="noopener noreferrer" >
                Connexion
            </Link>
        ),
        key: 'connexion',

    },

];




const Layout = ({ children }) => {


    const [current, setCurrent] = useState('mail');
    const onClick = (e) => {
        console.log('click ', e);
        setCurrent(e.key);
    };

  return (
    <>
      <Head>
        <title>Create Next App</title>
          <link rel="icon" href="planit_poker_logo-no-blanc.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
<div style={{width:'100vw',
    display:"flex",
    justifyContent:"center",}}>
    <Link href="/"   rel="noopener noreferrer">
            <Image
                alt="logo"
                src="/baniere_sans_blanc.png"
                width={600}
                height={200}
                style={{
                    width: 'auto',
                    height: '15vh',
                    display:"flex",
                    justifyContent:"center",
                }}
            />
        </Link>
        </div>

        <Menu onClick={onClick} selectedKeys={[current]} mode="horizontal" items={items} style={{borderRadius:'25px' ,width:'100vw', textAlign:'center',position:'relative', right:'8px',display:'flex',justifyContent:'center'}}   />

        {children}

        <footer>
            <div className="pub_footer">Développé par : Louka FAUVEL, Geoffrey LAUNAY et Paul GOUIN</div>
        </footer>
    </>

  );
};

export default Layout;