import Head from "next/head";
import React, {useState} from "react";
import {DownCircleTwoTone, MailOutlined, StepBackwardFilled} from '@ant-design/icons';
import {Menu} from "antd";





const items = [
    {
        label:  (<a href="/"   rel="noopener noreferrer">
            accueil
        </a>),
        key: 'mail',
        icon: <MailOutlined />,
    },

    {
        label: (
            <a href="/rooms/form"   rel="noopener noreferrer">
               inscription
            </a>
        ),
        key: 'alipay',
        icon:  <DownCircleTwoTone />,
    },
];




const Layout = ({ children }) => {


    const [current, setCurrent] = useState('mail');
    const onClick = (e) => {
        console.log('click ', e);
        setCurrent(e.key);
    };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <Menu onClick={onClick} selectedKeys={[current]} mode="horizontal" items={items} />
      {children}
      <footer>
      </footer>
    </>
  );
};

export default Layout;